### ISSUE TITLE
Specific settings for each solver

### ISSUE THREAD

**Issue by jadinm** [svissicchio/Repetita#7]
To add our solver to Repetita, we need more parameters that those currently available, like the maximum number of segments.
We also have other parameters that are very specific to our solver.

I see two solutions to allow any solver to have their specific settings:
1. We give all the extra arguments on the form "-extra arg1=value1,arg2=value2,arg3=value3"
2. We give a path to a yaml/json file that gives all these specific arguments: "-extra config.json"

I would prefer to implement the second one because it more flexible.
Do you have any preference ?

**Comment by svissicchio** [comment]
Not really, I have no specific preference.
Maybe the "-extra \<filename\>" option is more compact.
